 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/declaracaos", type: :request do
  # Declaracao. As you add validations to Declaracao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Declaracao.create! valid_attributes
      get declaracaos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      declaracao = Declaracao.create! valid_attributes
      get declaracao_url(declaracao)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_declaracao_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      declaracao = Declaracao.create! valid_attributes
      get edit_declaracao_url(declaracao)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Declaracao" do
        expect {
          post declaracaos_url, params: { declaracao: valid_attributes }
        }.to change(Declaracao, :count).by(1)
      end

      it "redirects to the created declaracao" do
        post declaracaos_url, params: { declaracao: valid_attributes }
        expect(response).to redirect_to(declaracao_url(Declaracao.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Declaracao" do
        expect {
          post declaracaos_url, params: { declaracao: invalid_attributes }
        }.to change(Declaracao, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post declaracaos_url, params: { declaracao: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested declaracao" do
        declaracao = Declaracao.create! valid_attributes
        patch declaracao_url(declaracao), params: { declaracao: new_attributes }
        declaracao.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the declaracao" do
        declaracao = Declaracao.create! valid_attributes
        patch declaracao_url(declaracao), params: { declaracao: new_attributes }
        declaracao.reload
        expect(response).to redirect_to(declaracao_url(declaracao))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        declaracao = Declaracao.create! valid_attributes
        patch declaracao_url(declaracao), params: { declaracao: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested declaracao" do
      declaracao = Declaracao.create! valid_attributes
      expect {
        delete declaracao_url(declaracao)
      }.to change(Declaracao, :count).by(-1)
    end

    it "redirects to the declaracaos list" do
      declaracao = Declaracao.create! valid_attributes
      delete declaracao_url(declaracao)
      expect(response).to redirect_to(declaracaos_url)
    end
  end
end
