 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/laudos", type: :request do
  # Laudo. As you add validations to Laudo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Laudo.create! valid_attributes
      get laudos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      laudo = Laudo.create! valid_attributes
      get laudo_url(laudo)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_laudo_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      laudo = Laudo.create! valid_attributes
      get edit_laudo_url(laudo)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Laudo" do
        expect {
          post laudos_url, params: { laudo: valid_attributes }
        }.to change(Laudo, :count).by(1)
      end

      it "redirects to the created laudo" do
        post laudos_url, params: { laudo: valid_attributes }
        expect(response).to redirect_to(laudo_url(Laudo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Laudo" do
        expect {
          post laudos_url, params: { laudo: invalid_attributes }
        }.to change(Laudo, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post laudos_url, params: { laudo: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested laudo" do
        laudo = Laudo.create! valid_attributes
        patch laudo_url(laudo), params: { laudo: new_attributes }
        laudo.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the laudo" do
        laudo = Laudo.create! valid_attributes
        patch laudo_url(laudo), params: { laudo: new_attributes }
        laudo.reload
        expect(response).to redirect_to(laudo_url(laudo))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        laudo = Laudo.create! valid_attributes
        patch laudo_url(laudo), params: { laudo: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested laudo" do
      laudo = Laudo.create! valid_attributes
      expect {
        delete laudo_url(laudo)
      }.to change(Laudo, :count).by(-1)
    end

    it "redirects to the laudos list" do
      laudo = Laudo.create! valid_attributes
      delete laudo_url(laudo)
      expect(response).to redirect_to(laudos_url)
    end
  end
end
