 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pareceres", type: :request do
  # Parecer. As you add validations to Parecer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Parecer.create! valid_attributes
      get pareceres_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      parecer = Parecer.create! valid_attributes
      get parecer_url(parecer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_parecer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      parecer = Parecer.create! valid_attributes
      get edit_parecer_url(parecer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Parecer" do
        expect {
          post pareceres_url, params: { parecer: valid_attributes }
        }.to change(Parecer, :count).by(1)
      end

      it "redirects to the created parecer" do
        post pareceres_url, params: { parecer: valid_attributes }
        expect(response).to redirect_to(parecer_url(Parecer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Parecer" do
        expect {
          post pareceres_url, params: { parecer: invalid_attributes }
        }.to change(Parecer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pareceres_url, params: { parecer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested parecer" do
        parecer = Parecer.create! valid_attributes
        patch parecer_url(parecer), params: { parecer: new_attributes }
        parecer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the parecer" do
        parecer = Parecer.create! valid_attributes
        patch parecer_url(parecer), params: { parecer: new_attributes }
        parecer.reload
        expect(response).to redirect_to(parecer_url(parecer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        parecer = Parecer.create! valid_attributes
        patch parecer_url(parecer), params: { parecer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested parecer" do
      parecer = Parecer.create! valid_attributes
      expect {
        delete parecer_url(parecer)
      }.to change(Parecer, :count).by(-1)
    end

    it "redirects to the pareceres list" do
      parecer = Parecer.create! valid_attributes
      delete parecer_url(parecer)
      expect(response).to redirect_to(pareceres_url)
    end
  end
end
