 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/relatorios", type: :request do
  # Relatorio. As you add validations to Relatorio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Relatorio.create! valid_attributes
      get relatorios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      relatorio = Relatorio.create! valid_attributes
      get relatorio_url(relatorio)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_relatorio_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      relatorio = Relatorio.create! valid_attributes
      get edit_relatorio_url(relatorio)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Relatorio" do
        expect {
          post relatorios_url, params: { relatorio: valid_attributes }
        }.to change(Relatorio, :count).by(1)
      end

      it "redirects to the created relatorio" do
        post relatorios_url, params: { relatorio: valid_attributes }
        expect(response).to redirect_to(relatorio_url(Relatorio.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Relatorio" do
        expect {
          post relatorios_url, params: { relatorio: invalid_attributes }
        }.to change(Relatorio, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post relatorios_url, params: { relatorio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested relatorio" do
        relatorio = Relatorio.create! valid_attributes
        patch relatorio_url(relatorio), params: { relatorio: new_attributes }
        relatorio.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the relatorio" do
        relatorio = Relatorio.create! valid_attributes
        patch relatorio_url(relatorio), params: { relatorio: new_attributes }
        relatorio.reload
        expect(response).to redirect_to(relatorio_url(relatorio))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        relatorio = Relatorio.create! valid_attributes
        patch relatorio_url(relatorio), params: { relatorio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested relatorio" do
      relatorio = Relatorio.create! valid_attributes
      expect {
        delete relatorio_url(relatorio)
      }.to change(Relatorio, :count).by(-1)
    end

    it "redirects to the relatorios list" do
      relatorio = Relatorio.create! valid_attributes
      delete relatorio_url(relatorio)
      expect(response).to redirect_to(relatorios_url)
    end
  end
end
