default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: db
  username: postgres
  password: postgres
  database: elephantrh_development

test:
  <<: *default
  database: ElephantRH_test

production:
  <<: *default
  database: elephant_prod
  username: elephant
  password: <%= ENV['ELEPHANTRH_DATABASE_PASSWORD'] %>
